app/__init__.py
from flask import Flask, render_template
from app.home import home_blueprint

app = Flask(__name__)

app.config['DEBUG'] = True

#OVERRIDE TEMPLATES
app.config['SECURITY_FORGOT_PASSWORD_TEMPLATE'] = 'security/forgot_password.html'
app.config['SECURITY_LOGIN_USER_TEMPLATE'] = 'security/login_user.html'
app.config['SECURITY_REGISTER_USER_TEMPLATE'] = 'security/register_user.html'
app.config['SECURITY_RESET_PASSWORD_TEMPLATE'] = 'security/reset_password.html'
app.config['SECURITY_CHANGE_PASSWORD_TEMPLATE'] = 'security/change_password.html'
app.config['SECURITY_SEND_CONFIRMATION_TEMPLATE'] = 'security/send_confirmation.html'
app.config['SECURITY_SEND_LOGIN_TEMPLATE'] = 'security/send_login.html'

#POST LOGIN VIEW
app.config['SECURITY_POST_LOGIN_VIEW'] = '/account'
app.config['SECURITY_POST_LOGOUT_VIEW'] = '/'

app.register_blueprint(home_blueprint, url_prefix='/')

@app.errorhandler(401)
def unauthorised(e):
    #TODO: Logger warning
    return render_template('401.html'), 401

@app.errorhandler(403)
def forbidden(e):
    #TODO: Logger warning
    return render_template('403.html'), 403

@app.errorhandler(404)
def page_not_found(e):
    #TODO: Logger warning
    return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
    #TODO: Logger warning
    return render_template('500.html'), 500

app/home/__init__.py
from app.home.views import home_blueprint

app/home/views.py
from datetime import datetime
from flask import render_template, Blueprint, current_app
from werkzeug.local import LocalProxy

home_blueprint = Blueprint('home', __name__, template_folder='templates')

#_security = LocalProxy(lambda: current_app.extensions['security'])

@home_blueprint.route('/', methods=["GET"])
def home():
    """Renders the home page."""

    #form = _security.login_form

    return render_template(
        'home/index.html',
        title='Home Page',
        year=datetime.now().year,
     #   login_user_form=form
    )

@home_blueprint.route('contact')
def contact():
    """Renders the contact page."""
    return render_template(
        'home/contact.html',
        title='Contact',
        year=datetime.now().year,
        message='Your contact page.'
    )

@home_blueprint.route('about')
def about():
    """Renders the about page."""
    return render_template(
        'home/about.html',
        title='About',
        year=datetime.now().year,
        message='Your application description page.'
    )

app/templates/401.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>401 - Unauthorised</h1>
        <p>
            You must login to be able to use that resource
        </p>
    </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }} - My Flask Application</title>

    <link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" type="text/css" href="/static/content/site.css" /> -->

    {% block custom_css %}{% endblock %}

    <script src="/static/vendor/modernizr/modernizr.js"></script>
</head>

<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{{ url_for('home.home') }}" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('home.about') }}">About</a></li>
                    <li><a href="{{ url_for('home.contact') }}">Contact</a></li>
                </ul>
            </div>

            {% block user_info %}{% endblock %}
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - My Flask Application</p>
        </footer>
    </div>

    <script src="/static/vendor/jquery/dist/jquery.js"></script>
    <script src="/static/vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/static/vendor/respond/dest/respond.src.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/security/change_password.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% from "macros/_security_macros.html" import render_field_with_bootstrap_errors %}
{% include "security/_messages.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h1>{{ _('Change password') }}</h1>
        <form
            action="{{ url_for_security('change_password') }}"
            method="POST"
            name="change_password_form"
        >
          {{ change_password_form.hidden_tag() }}
          {{ render_field_with_bootstrap_errors(change_password_form.password, class="form-control") }}
          {{ render_field_with_bootstrap_errors(change_password_form.new_password, class="form-control") }}
          {{ render_field_with_bootstrap_errors(change_password_form.new_password_confirm, class="form-control") }}
          {{ render_field(change_password_form.submit, class_="btn btn-primary") }}
        </form>
    </div>
</div>

{%  endblock %}

app/templates/security/forgot_password.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h1>{{ _('Send password reset instructions') }}</h1>
        <form
            action="{{ url_for_security('forgot_password') }}"
            method="POST"
            name="forgot_password_form"
        >
            {{ forgot_password_form.hidden_tag() }}
            {{ render_field_with_errors(forgot_password_form.email, class="form-control") }}
            {{ render_field(forgot_password_form.submit, class_="btn btn-primary") }}
        </form>
        {% include "security/_menu.html" %}
    </div>
</div>

{% endblock %}

app/templates/security/login_user.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% from "macros/_security_macros.html" import render_field_with_bootstrap_errors %}


{% block content %}

<div class="row">
    <div class="col-md-6">
        <h1>{{ _('Login') }}</h1>

        {% include "security/_messages.html" %}

        <form
            action="{{ url_for_security('login') }}"
            method="POST"
            name="login_user_form"
        >
            {{ login_user_form.hidden_tag() }}
            {{ render_field_with_bootstrap_errors(login_user_form.email, class="form-control") }}
            {{ render_field_with_bootstrap_errors(login_user_form.password, class="form-control") }}
            {{ render_field_with_errors(login_user_form.remember, class="checkbox") }}
            {{ render_field(login_user_form.next) }}
            {{ render_field(login_user_form.submit, class_="btn btn-primary") }}
        </form>
    </div>
</div>

{# {% include "security/_menu.html" %} #}

{% endblock %}

app/templates/security/register_user.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% from "macros/_security_macros.html" import render_field_with_bootstrap_errors %}
{% include "security/_messages.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h1>{{ _('Register') }}</h1>

        <form
            action="{{ url_for_security('register') }}"
            method="POST"
            name="register_user_form"
        >
            {{ register_user_form.hidden_tag() }}
            {{ render_field_with_bootstrap_errors(register_user_form.email, class="form-control") }}
            {{ render_field_with_bootstrap_errors(register_user_form.password, class="form-control") }}

            {% if register_user_form.password_confirm %}
                {{ render_field_with_bootstrap_errors(register_user_form.password_confirm, class="form-control") }}
            {% endif %}

            {{ render_field(register_user_form.submit, class_="btn btn-primary") }}
        </form>

        {% include "security/_menu.html" %}
    </div>
</div>

{% endblock %}

app/templates/security/reset_password.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h1>{{ _('Reset password') }}</h1>
        <form
            action="{{ url_for_security('reset_password', token=reset_password_token) }}"
            method="POST"
            name="reset_password_form"
        >
            {{ reset_password_form.hidden_tag() }}
            {{ render_field_with_bootstrap_errors(reset_password_form.password, class="form-control") }}
            {{ render_field_with_bootstrap_errors(reset_password_form.password_confirm, class="form-control") }}
            {{ render_field(reset_password_form.submit, class_="btn btn-primary") }}
        </form>
        {% include "security/_menu.html" %}
    </div>
</div>

{% endblock %}

app/templates/security/send_confirmation.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

{% block content %}

<h1>{{ _('Resend confirmation instructions') }}</h1>
<form
    action="{{ url_for_security('send_confirmation') }}"
    method="POST"
    name="send_confirmation_form"
>
    {{ send_confirmation_form.hidden_tag() }}
    {{ render_field_with_errors(send_confirmation_form.email) }}
    {{ render_field(send_confirmation_form.submit) }}
</form>
{% include "security/_menu.html" %}

{% endblock %}

app/templates/security/send_login.html
{% extends "layout.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

{% block content %}

<h1>{{ _('Login') }}</h1>
<form
    action="{{ url_for_security('login') }}"
    method="POST"
    name="send_login_form"
    class="form-control">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit) }}
</form>
{% include "security/_menu.html" %}

{% endblock %}